table DimGenres
	lineageTag: 059640f1-7dc1-4d26-9394-062475ba33c9

	measure 'Total Genres' = COUNT(DimGenres[genres])
		formatString: 0
		lineageTag: f78ce078-bcc0-40e7-a043-6b0892224a4b

	measure 'Genres Rank' =
			
			RANKX(
			    ALL(DimGenres),
			    CALCULATE(MAX(DimGenres[Count])),
			    ,
			    DESC,
			    Dense
			)
		formatString: 0
		lineageTag: 298ba567-da61-4fd5-9234-a7038161764e

	measure 'Top Genre KPI' =
			
			VAR TopGenre =
			    TOPN(
			        1,
			        ALL(DimGenres[genres]),
			        [Total Movies],
			        DESC
			    )
			VAR GenreName =
			    CONCATENATEX(TopGenre, DimGenres[genres], ", ")
			VAR MovieCount =
			    MAXX(TopGenre, [Total Movies])
			RETURN
			    GenreName & " (" & FORMAT(MovieCount, "#,##0") & " Movies)"
		lineageTag: bc80669f-9ae8-4896-9e65-04b798cd9bc8

	measure 'Lowest Rated Genre KPI' =
			
			VAR LowestGenre =
			    TOPN(
			        1,
			        ALL(DimGenres[genres]),
			        [Average of Total Rating],
			        ASC
			    )
			VAR GenreName =
			    CONCATENATEX(LowestGenre, DimGenres[genres], ", ")
			VAR Rating =
			    MAXX(LowestGenre, [Average of Total Rating])
			RETURN
			    GenreName & " (" & FORMAT(Rating, "0.00") & ")"
		lineageTag: 21566066-7ceb-4c10-b8d7-88f41d54a3cf

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 925b6b37-51fa-4035-ac72-bb745393d333
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column genres
		dataType: string
		lineageTag: 09b8904b-9ba8-41b1-87bc-e2438388d420
		summarizeBy: none
		sourceColumn: genres

		annotation SummarizationSetBy = Automatic

	column Count
		dataType: int64
		formatString: 0
		lineageTag: 83bf56fa-5a3f-4acf-b538-9f5f1dd79daa
		summarizeBy: none
		sourceColumn: Count

		annotation SummarizationSetBy = Automatic

	partition DimGenres = m
		mode: import
		source =
				let
				    Source = Movies,
				    #"Grouped Rows" = Table.Group(Source, {"genres"}, {{"Count", each Table.RowCount(_), Int64.Type}}),
				    #"Added Index" = Table.AddIndexColumn(#"Grouped Rows", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "genres", "Count"}),
				    #"Removed Bottom Rows" = Table.RemoveLastN(#"Reordered Columns",1)
				in
				    #"Removed Bottom Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

