table DimGenres
	lineageTag: 059640f1-7dc1-4d26-9394-062475ba33c9

	measure 'Count Of Genres' = COUNT(DimGenres[genres])
		lineageTag: 11c11205-6be3-440f-af81-a50405e22f3d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Genres %' =
			
			DIVIDE(
			    [Count Of Total Movies],
			    CALCULATE(
			        [Count Of Total Movies],
			        REMOVEFILTERS(DimGenres[genres])
			    ),
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d53351f7-9df4-4b26-855c-6d76269e275d

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 925b6b37-51fa-4035-ac72-bb745393d333
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column genres
		dataType: string
		lineageTag: 09b8904b-9ba8-41b1-87bc-e2438388d420
		summarizeBy: none
		sourceColumn: genres

		annotation SummarizationSetBy = Automatic

	column Count
		dataType: int64
		formatString: 0
		lineageTag: 83bf56fa-5a3f-4acf-b538-9f5f1dd79daa
		summarizeBy: none
		sourceColumn: Count

		annotation SummarizationSetBy = Automatic

	partition DimGenres = m
		mode: import
		source =
				let
				    Source = Movies,
				    #"Grouped Rows" = Table.Group(Source, {"genres"}, {{"Count", each Table.RowCount(_), Int64.Type}}),
				    #"Added Index" = Table.AddIndexColumn(#"Grouped Rows", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "genres", "Count"}),
				    #"Removed Bottom Rows" = Table.RemoveLastN(#"Reordered Columns",1)
				in
				    #"Removed Bottom Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

